# Generated by Django 5.0.6 on 2024-05-24 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Вид продукта', 'verbose_name_plural': 'Виды продуктов'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+375XXXXXXXXX'.", regex='((\\+375)?(29|33|44|25)\\d{7})')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_name',
            field=models.CharField(max_length=50, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturing_status',
            field=models.CharField(choices=[('PROD_STOP', 'Снято с производства'), ('IN_PROD', 'В производстве')], max_length=20, verbose_name='Состояние производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGI.model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGI.producttype', verbose_name='Вид продукта'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type_name',
            field=models.CharField(max_length=100, verbose_name='Название вида'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGI.client', verbose_name='Клиент заказчик'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_fulfillment',
            field=models.DateField(verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_order',
            field=models.DateField(verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGI.product', verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество продукта'),
        ),
    ]
