# Generated by Django 5.0.6 on 2024-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0002_faqmodel_alter_client_options_alter_model_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название статьи')),
                ('full_text', models.TextField(verbose_name='Текст статьи')),
                ('first_sentence', models.CharField(max_length=500, verbose_name='Первое предложение')),
                ('date', models.DateField(verbose_name='Дата статьи')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
