# Generated by Django 5.0.6 on 2024-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_sentence',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Первое предложение'),
        ),
    ]
