# Generated by Django 5.0.6 on 2024-05-31 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0005_remove_client_code_client_is_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название промокода')),
                ('discount', models.FloatField(validators=[django.core.validators.RegexValidator(message='Скидка должна быть введена в формате: 1 или 0.XX', regex='^1|0\\.\\d{2}$')], verbose_name='Скидка')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+375XXXXXXXXX'.", regex='((\\+375)?(29|33|44|25)\\d{7})')], verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
