# Generated by Django 5.0.6 on 2024-05-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0006_promocode_alter_client_phone_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
