# Generated by Django 5.0.6 on 2024-05-31 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0008_alter_promocode_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.RegexValidator(message='Скидка должна быть введена в формате: 1 или 0.XX', regex='^1|0\\.\\d{2}$')], verbose_name='Скидка'),
        ),
    ]
