# Generated by Django 5.0.6 on 2024-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
