# Generated by Django 5.0.6 on 2024-06-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0013_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='article_photos/'),
        ),
    ]
