# Generated by Django 5.0.6 on 2024-05-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0003_alter_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
