# Generated by Django 5.0.6 on 2024-05-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0004_delete_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Название модели'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
