# Generated by Django 5.0.6 on 2024-09-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0014_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_of_order',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа'),
        ),
    ]
