# Generated by Django 5.0.6 on 2024-05-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0005_alter_product_model_delete_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код мебели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование мебели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('kitchen', 'Кухонная'), ('office', 'Офисная'), ('cabinet', 'Кабинетная')], max_length=40, verbose_name='Вид мебели'),
        ),
    ]
