# Generated by Django 5.0.6 on 2024-06-02 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0006_alter_product_code_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='client_company',
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
