# Generated by Django 5.0.6 on 2024-06-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0008_alter_sales_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_of_fulfillment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
