# Generated by Django 5.0.6 on 2024-06-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0010_sales_promo_code_alter_sales_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Промокод'),
        ),
    ]
