# Generated by Django 5.0.6 on 2024-05-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('kitchen', 'Кухонный'), ('office', 'Офисный'), ('cabinet', 'Кабинетный')], max_length=40, verbose_name='Вид продукта'),
        ),
    ]
