# Generated by Django 5.0.6 on 2024-09-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0015_alter_sales_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_of_order',
            field=models.DateField(default='2024-09-10', verbose_name='Дата заказа'),
        ),
    ]
