# Generated by Django 5.0.6 on 2024-09-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0016_alter_sales_date_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.FloatField(default=0, verbose_name='Цена заказа'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_order',
            field=models.DateField(blank=True, default='2024-09-11', verbose_name='Дата заказа'),
        ),
    ]
