# Generated by Django 5.0.6 on 2024-09-17 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0017_sales_total_alter_sales_date_of_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_order',
            field=models.DateField(blank=True, default='2024-09-17', verbose_name='Дата заказа'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='IGI.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='cart_items', to='IGI.cartitem')),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGI.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IGI.sales')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(through='IGI.SalesItem', to='IGI.product'),
        ),
    ]
