# Generated by Django 5.0.6 on 2024-09-18 13:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGI', '0019_cartitem_cart_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='salesitem',
            options={},
        ),
        migrations.AddField(
            model_name='faqmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 18, 13, 3, 51, 558514, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='IGI.product'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_of_order',
            field=models.DateField(blank=True, default='2024-09-18', verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(through='IGI.SalesItem', to='IGI.product', verbose_name='Продукты'),
        ),
    ]
